### ISSUE TITLE
Clarify readme

### ISSUE THREAD

**Issue by pancetta** [jakob-fritz/github2lab_action#17]
Looks like a few things are outdated/unclear in the readme:

- [x] The file `mirror_wait.yml` does not exist in the examples
- [x] The `get_status` modus waits for the CI jobs to complete (or fail), this should be clarified.
- [x] ... tbc

**Comment by jakob-fritz** [comment]
The file `mirror_wait.yml` is only used for the testing of the action itself, but not used for productive use by others. Shall it be mentioned in the README nevertheless?

The `get_status` will be explained more in the Readme. Thanks for the hint.

**Comment by pancetta** [comment]
Look at the first point here: https://github.com/jakob-fritz/github2lab_action#github-ci

**Comment by jakob-fritz** [comment]
Thank you, I missed that one. It is outdated, indeed.

**Comment by jakob-fritz** [comment]
Can you check if #22 works for you? Sadly I cannot assign you as reviewer in that pull-request. This is why I write it here.

**Comment by pancetta** [comment]
Nice!
