### ISSUE TITLE
Does this still work when updates to multiple branches are pushed?

### ISSUE THREAD

**Issue by pancetta** [jakob-fritz/github2lab_action#21]
Mirroring works and Gitlab will run jobs for all these updated branches, but what will `get_status` do?

**Comment by jakob-fritz** [comment]
`get_status` works with multiple branches pushed in parallel. `get_status` queries the latest pipeline-id (from gitlab) for the commit-hash (that Github actions runs for).

Therefore, multiple branches do not pose a problem, as "only" multiple actions and multiple pipelines are triggered.

However, running multiple jobs for mirroring in parallel sometimes poses a problem, as locking and updating the remote repo is not possible, when multiple jobs try to access at the same time.

**Comment by pancetta** [comment]
Thanks for the clarification!

**Comment by jakob-fritz** [comment]
After a conversation I got it as only the current branch shall be pushed to gitlab. Starting to implement this
