### ISSUE TITLE
Deleting protected branches 

### ISSUE THREAD

**Issue by pancetta** [jakob-fritz/github2lab_action#27]
Check out this CI run: https://github.com/brownbaerchen/pySDC/actions/runs/3846618390/jobs/6625496489

It looks like the fork tries to delete branches from the gitlab repository, which is failing (and rightfully so, I would say). Any ideas?

**Comment by jakob-fritz** [comment]
@brownbaerchen, could you try and replace https://github.com/brownbaerchen/pySDC/blob/798c925b97c91f2cd2d2a9332f9ab569c368ee4c/.github/workflows/ci_pipeline.yml#L47
with `jakob-fritz/github2lab_action@Iss27_forked_repo` ? I tried a fix in that new branch (not deleting any branches).
If this works, I will include it in the main branch (adding another Parameter)

**Comment by brownbaerchen** [comment]
Sure, [here](https://github.com/brownbaerchen/pySDC/actions/runs/3892243512/jobs/6643431181) is the output. Seems to work fine!
