### ISSUE TITLE
Can anyone start a PR?

### ISSUE THREAD

**Issue by brownbaerchen** [jakob-fritz/github2lab_action#29]
Before Robert gave me a token, the mirroring would fail in pull requests like [here](https://github.com/Parallel-in-Time/pySDC/actions/runs/3873541314/jobs/6603680746).

So what happens if some one without a token opens a PR? The pipeline fails? Maybe this is necessary for political/security reasons?

**Comment by jakob-fritz** [comment]
For the action to work in pull-requests, the Job needs to run `on: pull_request_target` instead of `on: pull_request`. With this, the project-secrets from the target-repo are used -> the GitLab-Token can be accessed.
I forgot to mention that in the Readme. I will add it.
