### ISSUE TITLE
Gitlab-Pipeline is not always triggered on push

### ISSUE THREAD

**Issue by jakob-fritz** [jakob-fritz/github2lab_action#31]
Sometimes, the Gitlab-CI-Pipeline does not start after new commits have been pushed to Gitlab (via the action). Therefore, a later job fails, that tries to get info on the pipeline (that does not exist, because it never started).

Find out why the pipeline is not always triggered and how to fix this

**Comment by pancetta** [comment]
Did that happened here? 
https://github.com/Parallel-in-Time/pySDC/actions/runs/3892679527/jobs/6644425428

**Comment by pancetta** [comment]
Is it reproducible? I.e. does it depend on the job?

**Comment by jakob-fritz** [comment]
Unfortunately it is not reproducible. I.e. when pushing a new commit to the same branch, the pipeline starts (without renaming branches and with still pushing multiple branches in parallel).

I find ways to manually trigger pipelines e.g. by webhooks or using curl, but this seems inappropriate, as most of the time, the simple push suffices to trigger the pipeline (and triggering the pipeline twice should be avoided).

**Comment by pancetta** [comment]
But it looks like re-running the affected pipeline on GitHub reproduces the error..

**Comment by jakob-fritz** [comment]
One Idea, that came to my mind is that the linked commit is the first, after someone else mirrored, i.e. many references changed in the repo. Maybe it is an issue with Gitlab to determine where to run pipelines, resulting in not starting any.

A possible way to avoid this behaviour might be manual triggering of a pipeline for the current commit (maybe checking if any are running, and starting them if not already running)

**Comment by pancetta** [comment]
Hmm.. can you reproduce this (broken after mirroring by fork)? And: what do you mean by "manual triggering"?

**Comment by jakob-fritz** [comment]
Manual triggering: Gitlab offers the possibility to trigger the start of a pipeline via the API & via a webhook (after creating trigger-tokens). See [Gitlab API Documentation](https://docs.gitlab.com/ee/ci/triggers/#trigger-pipelines-by-using-the-api)

**Comment by jakob-fritz** [comment]
Unfortunately I could not reproduce the issue when I tried to mirror from a second repo. So I cannot pinpoint where the issue arises from.

One idea from my side would be to stop mirroring from multiple repos and instead do this via pull-requests (when marking them as draft it is obvious, that they should not be merged).

@pancetta Is this a doable approach?

**Comment by jakob-fritz** [comment]
Closing because this issue seems stale.
If it pops up, please ask to reopen the issue or file a new one
